### ISSUE TITLE
Borderless Fullscreen doesnt respect fullscreen resolution setting

### ISSUE THREAD

**Issue by 0tii** [Kir-Antipov/cubes-without-borders#25]
When using borderless fullscreen, the resolution is not adjusted to the selected fullscreen resolution. The only reason for me to take this over just maximizing the minecraft window was to play in 1080p on my 4k monitor. With this its always 4k.

**Comment by Kir-Antipov** [comment]
"Hey, waiter, there's milk in my cappuccino!"

Hi! I think you're a bit confused :) The whole point of borderless fullscreen is that it functions like a maximized window without a border *(hence, "borderless")*. While it's not *exactly* the same, it's a close enough approximation for regular folks to understand. You can't change the "screen resolution" for a floating window, and you also can't change it for a borderless fullscreen window.

**Comment by 0tii** [comment]
@Kir-Antipov I am able to change resolution in Borderless Fullscreen for basically all commercial games, be it Borderlands, CSGO or Dead Space. Not far fetched to expect it here too.

**Comment by 0tii** [comment]
@Kir-Antipov I am able to change resolution in Borderless Fullscreen for basically all commercial games, be it Borderlands, CSGO or Dead Space. Not far fetched to expect it here too. Im allergic to this passively insultive arrogant writing style of yours btw.

**For everyone with a similar problem, there are of course some talented people who made a mod for exactly this to work, so check out this mod** (or any of its previous forks for versions lower than 1.21): https://modrinth.com/mod/resolutioncontrol3

It allows you to change the render resolution in windowed mode, which according to mister antipov here, is not possible and together with the borderless mod, this achieves exactly what I asked here and what other games do: it allows to change the render resolution in fullscreen bordered.

**Comment by 0tii** [comment]
@Kir-Antipov I am able to change resolution in Borderless Fullscreen for basically all commercial games, be it Borderlands, CSGO or Dead Space. Not far fetched to expect it here too.

**For everyone with a similar problem, there are of course some talented people who made a mod for exactly this to work, so check out this mod** (or any of its previous forks for versions lower than 1.21): https://modrinth.com/mod/resolutioncontrol3

Together with the borderless mod, this achieves exactly that: it allows to change the render resolution in fullscreen bordered.

**Comment by Kir-Antipov** [comment]
> I am able to change resolution in Borderless Fullscreen for basically all commercial games, be it Borderlands, CSGO or Dead Space. Not far fetched to expect it here too.

Let's start with a side note: demanding a feature, whatever it may be, in a project run entirely by unpaid hobbyist(s), which is mostly how the entire modding field for any game operates, based on the premise that some commercial project, backed by a megacorporation with millions of dollars on its hands, has it - is not what I would personally call an empathetic, non-sociopathic, or generally appealing argument. Thus, I would kindly advise refraining from using it whenever you have a dialogue with any mod developer.

Back to the topic at hand. While these games may call it "screen resolution" *(also, I honestly don't recall Dead Space supporting borderless fullscreen at all)*, it's not what you actually change, because you simply cannot change the **screen** resolution for a specific app and not for everything else, duh. You actually change the in-game scaling factor to inefficiently imitate the work that would have otherwise been done by The Powers Above. And Minecraft simply doesn't have that feature in place. While it's somewhat trivial to re-implement, I don't see why it should be done by a mod that focuses on window properties *(which is, thanks to Windows, already a finicky topic, even though it shouldn't be)* rather than on the rendering pipeline. Yeah, this feature is definitely useful here. However, it has implications beyond borderless fullscreen; for example, it may also be used in conjunction with the regular windowed mode. Thus, this whole endeavor would be much better handled by a separate mod that can focus its attention solely on the rendering aspect of the game. Which, as you mentioned yourself, somebody has already done. Kudos to them! Go at least give the developer a star and maybe a few nice words of encouragement, as with that download count I can see how they might stop updating the project the moment they stop using it themself.

**Comment by 0tii** [comment]
Your writing style is absolutely condescending, especially given you're basing it upon statements that I haven't made. Never did I talk about 'screen resolution'. I also did not demand a feature, but rather expected your mod to provide functionality that is a logical consequence of it's merit. A plain misunderstanding based on my experience with borderless fullscreen in almost every other game.

Thanks nonetheless for the belittling tone from the beginning on, great tell of character.

**Comment by Kir-Antipov** [comment]
> Your writing style is absolutely condescending

I do apologize if it seemed that way! This was not my intention, and I certainly didn't want to hurt or offend you in any way. My aim was to explain how this functionality works and, therefore, why I consider it outside the scope of this project, in a somewhat dry and formal manner. Since being formal is not my strongest suit, I can see how a dry text mixed with phrases like "duh" and other casual slips might come across as it did. I'm sorry I didn't convey my message in a more friendly manner.

> Never did I talk about 'screen resolution'.

Well, we kinda did talk about it, or at least I did, because this whole issue centers around the difference between changing the screen resolution and the in-game scaling factor, while, as you pointed out, in some games that support the latter, these options are hidden behind the same setting.

> I also did not demand a feature

I guess I misread your message as having a more demanding tone than was intended. Unfortunately, it’s not uncommon to see people quite literally demanding things from unpaid or poorly paid FOSS developers while criticizing their work for not perfectly matching something they saw in the commercial space. The first part of your response triggered that association for me.

> A plain misunderstanding

And let's leave it at that. Once again, I apologize if I appeared on a snobbish side of things. I hope there are no hard feelings! :)

**Comment by GuyFromTheInternet** [comment]
Just wanted to suggest that, but well, yea that didnt go so well

**Comment by Kir-Antipov** [comment]
I went back to the mod, refactored it a bit, and, in the process, reconsidered some of my life choices. This is, in fact, a feature a typical user would expect to see right out of the box. Maybe I should have listened to the feedback instead of immediately switching to pedantic mode and explaining why it doesn't already work and why it makes sense from the technical point of view, even though it defies expectations of regular players.

**Comment by Kir-Antipov** [comment]
Software scaling is now supported out of the box and is integrated with the screen resolution settings. Thank you for the suggestion! It turned out to be quite helpful, even beyond the scope of borderless fullscreen, as GLFW doesn't support changing screen resolution on macOS and Linux+Wayland at all!
